//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_SAMBILAN_SALARY(Nullable<decimal> bULAN, Nullable<decimal> tAHUN, ObjectParameter tEXT)
        {
            var bULANParameter = bULAN.HasValue ?
                new ObjectParameter("BULAN", bULAN) :
                new ObjectParameter("BULAN", typeof(decimal));
    
            var tAHUNParameter = tAHUN.HasValue ?
                new ObjectParameter("TAHUN", tAHUN) :
                new ObjectParameter("TAHUN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAMBILAN_SALARY", bULANParameter, tAHUNParameter, tEXT);
        }
    
        public virtual int ZATUL_INSERT_KEW_GERAK_GAJI2(Nullable<decimal> pI_BULAN, Nullable<decimal> pI_TAHUN, string pI_NO_PEKERJA, string pI_BUTIR, string pI_JENIS, string pI_PERINGKAT, string pI_TAHAP, string pI_NP_FINALISED_HR, string pI_NO_SURAT, string pI_NP_UBAH_HR, string pI_GRED)
        {
            var pI_BULANParameter = pI_BULAN.HasValue ?
                new ObjectParameter("PI_BULAN", pI_BULAN) :
                new ObjectParameter("PI_BULAN", typeof(decimal));
    
            var pI_TAHUNParameter = pI_TAHUN.HasValue ?
                new ObjectParameter("PI_TAHUN", pI_TAHUN) :
                new ObjectParameter("PI_TAHUN", typeof(decimal));
    
            var pI_NO_PEKERJAParameter = pI_NO_PEKERJA != null ?
                new ObjectParameter("PI_NO_PEKERJA", pI_NO_PEKERJA) :
                new ObjectParameter("PI_NO_PEKERJA", typeof(string));
    
            var pI_BUTIRParameter = pI_BUTIR != null ?
                new ObjectParameter("PI_BUTIR", pI_BUTIR) :
                new ObjectParameter("PI_BUTIR", typeof(string));
    
            var pI_JENISParameter = pI_JENIS != null ?
                new ObjectParameter("PI_JENIS", pI_JENIS) :
                new ObjectParameter("PI_JENIS", typeof(string));
    
            var pI_PERINGKATParameter = pI_PERINGKAT != null ?
                new ObjectParameter("PI_PERINGKAT", pI_PERINGKAT) :
                new ObjectParameter("PI_PERINGKAT", typeof(string));
    
            var pI_TAHAPParameter = pI_TAHAP != null ?
                new ObjectParameter("PI_TAHAP", pI_TAHAP) :
                new ObjectParameter("PI_TAHAP", typeof(string));
    
            var pI_NP_FINALISED_HRParameter = pI_NP_FINALISED_HR != null ?
                new ObjectParameter("PI_NP_FINALISED_HR", pI_NP_FINALISED_HR) :
                new ObjectParameter("PI_NP_FINALISED_HR", typeof(string));
    
            var pI_NO_SURATParameter = pI_NO_SURAT != null ?
                new ObjectParameter("PI_NO_SURAT", pI_NO_SURAT) :
                new ObjectParameter("PI_NO_SURAT", typeof(string));
    
            var pI_NP_UBAH_HRParameter = pI_NP_UBAH_HR != null ?
                new ObjectParameter("PI_NP_UBAH_HR", pI_NP_UBAH_HR) :
                new ObjectParameter("PI_NP_UBAH_HR", typeof(string));
    
            var pI_GREDParameter = pI_GRED != null ?
                new ObjectParameter("PI_GRED", pI_GRED) :
                new ObjectParameter("PI_GRED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ZATUL_INSERT_KEW_GERAK_GAJI2", pI_BULANParameter, pI_TAHUNParameter, pI_NO_PEKERJAParameter, pI_BUTIRParameter, pI_JENISParameter, pI_PERINGKATParameter, pI_TAHAPParameter, pI_NP_FINALISED_HRParameter, pI_NO_SURATParameter, pI_NP_UBAH_HRParameter, pI_GREDParameter);
        }
    
        public virtual int ZATUL_UPDATE_KEW_GERAK_GAJI2(Nullable<decimal> pI_BULAN, Nullable<decimal> pI_TAHUN, string pI_NO_PEKERJA, string pI_BUTIR, string pI_JENIS, string pI_PERINGKAT, string pI_TAHAP, string pI_NP_FINALISED_HR, string pI_NP_FINALISED_IND_HR, string pI_NO_SURAT, string pI_NP_UBAH_HR, string pI_GRED, Nullable<decimal> kEW8ID, Nullable<System.DateTime> pI_TARIKH_MULA, string pI_KOD_PELARASAN)
        {
            var pI_BULANParameter = pI_BULAN.HasValue ?
                new ObjectParameter("PI_BULAN", pI_BULAN) :
                new ObjectParameter("PI_BULAN", typeof(decimal));
    
            var pI_TAHUNParameter = pI_TAHUN.HasValue ?
                new ObjectParameter("PI_TAHUN", pI_TAHUN) :
                new ObjectParameter("PI_TAHUN", typeof(decimal));
    
            var pI_NO_PEKERJAParameter = pI_NO_PEKERJA != null ?
                new ObjectParameter("PI_NO_PEKERJA", pI_NO_PEKERJA) :
                new ObjectParameter("PI_NO_PEKERJA", typeof(string));
    
            var pI_BUTIRParameter = pI_BUTIR != null ?
                new ObjectParameter("PI_BUTIR", pI_BUTIR) :
                new ObjectParameter("PI_BUTIR", typeof(string));
    
            var pI_JENISParameter = pI_JENIS != null ?
                new ObjectParameter("PI_JENIS", pI_JENIS) :
                new ObjectParameter("PI_JENIS", typeof(string));
    
            var pI_PERINGKATParameter = pI_PERINGKAT != null ?
                new ObjectParameter("PI_PERINGKAT", pI_PERINGKAT) :
                new ObjectParameter("PI_PERINGKAT", typeof(string));
    
            var pI_TAHAPParameter = pI_TAHAP != null ?
                new ObjectParameter("PI_TAHAP", pI_TAHAP) :
                new ObjectParameter("PI_TAHAP", typeof(string));
    
            var pI_NP_FINALISED_HRParameter = pI_NP_FINALISED_HR != null ?
                new ObjectParameter("PI_NP_FINALISED_HR", pI_NP_FINALISED_HR) :
                new ObjectParameter("PI_NP_FINALISED_HR", typeof(string));
    
            var pI_NP_FINALISED_IND_HRParameter = pI_NP_FINALISED_IND_HR != null ?
                new ObjectParameter("PI_NP_FINALISED_IND_HR", pI_NP_FINALISED_IND_HR) :
                new ObjectParameter("PI_NP_FINALISED_IND_HR", typeof(string));
    
            var pI_NO_SURATParameter = pI_NO_SURAT != null ?
                new ObjectParameter("PI_NO_SURAT", pI_NO_SURAT) :
                new ObjectParameter("PI_NO_SURAT", typeof(string));
    
            var pI_NP_UBAH_HRParameter = pI_NP_UBAH_HR != null ?
                new ObjectParameter("PI_NP_UBAH_HR", pI_NP_UBAH_HR) :
                new ObjectParameter("PI_NP_UBAH_HR", typeof(string));
    
            var pI_GREDParameter = pI_GRED != null ?
                new ObjectParameter("PI_GRED", pI_GRED) :
                new ObjectParameter("PI_GRED", typeof(string));
    
            var kEW8IDParameter = kEW8ID.HasValue ?
                new ObjectParameter("KEW8ID", kEW8ID) :
                new ObjectParameter("KEW8ID", typeof(decimal));
    
            var pI_TARIKH_MULAParameter = pI_TARIKH_MULA.HasValue ?
                new ObjectParameter("PI_TARIKH_MULA", pI_TARIKH_MULA) :
                new ObjectParameter("PI_TARIKH_MULA", typeof(System.DateTime));
    
            var pI_KOD_PELARASANParameter = pI_KOD_PELARASAN != null ?
                new ObjectParameter("PI_KOD_PELARASAN", pI_KOD_PELARASAN) :
                new ObjectParameter("PI_KOD_PELARASAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ZATUL_UPDATE_KEW_GERAK_GAJI2", pI_BULANParameter, pI_TAHUNParameter, pI_NO_PEKERJAParameter, pI_BUTIRParameter, pI_JENISParameter, pI_PERINGKATParameter, pI_TAHAPParameter, pI_NP_FINALISED_HRParameter, pI_NP_FINALISED_IND_HRParameter, pI_NO_SURATParameter, pI_NP_UBAH_HRParameter, pI_GREDParameter, kEW8IDParameter, pI_TARIKH_MULAParameter, pI_KOD_PELARASANParameter);
        }
    
        public virtual int SP_SAMBILAN_SALARY_TEST(Nullable<decimal> bULAN, Nullable<decimal> tAHUN, ObjectParameter tEXT)
        {
            var bULANParameter = bULAN.HasValue ?
                new ObjectParameter("BULAN", bULAN) :
                new ObjectParameter("BULAN", typeof(decimal));
    
            var tAHUNParameter = tAHUN.HasValue ?
                new ObjectParameter("TAHUN", tAHUN) :
                new ObjectParameter("TAHUN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAMBILAN_SALARY_TEST", bULANParameter, tAHUNParameter, tEXT);
        }
    }
}
