//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=SPGEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_EFT_KWSP_SAMBILAN(Nullable<decimal> pI_TAHUN, Nullable<decimal> pI_BULAN, ObjectParameter tEXT)
        {
            var pI_TAHUNParameter = pI_TAHUN.HasValue ?
                new ObjectParameter("PI_TAHUN", pI_TAHUN) :
                new ObjectParameter("PI_TAHUN", typeof(decimal));
    
            var pI_BULANParameter = pI_BULAN.HasValue ?
                new ObjectParameter("PI_BULAN", pI_BULAN) :
                new ObjectParameter("PI_BULAN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EFT_KWSP_SAMBILAN", pI_TAHUNParameter, pI_BULANParameter, tEXT);
        }
    
        public virtual int SP_SOCSO_SAMBILAN(Nullable<decimal> bULAN, Nullable<decimal> tAHUN, ObjectParameter tEXT)
        {
            var bULANParameter = bULAN.HasValue ?
                new ObjectParameter("BULAN", bULAN) :
                new ObjectParameter("BULAN", typeof(decimal));
    
            var tAHUNParameter = tAHUN.HasValue ?
                new ObjectParameter("TAHUN", tAHUN) :
                new ObjectParameter("TAHUN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SOCSO_SAMBILAN", bULANParameter, tAHUNParameter, tEXT);
        }
    }
}
